[main]
# Font
font=Hack Nerd Font:size=12.5
line-height=22

# Padding around terminal content
pad=10x10

[csd]
preferred=none
size=0

[cursor]
style=beam
blink=yes

[colors]
# Background & Foreground
background=1e1e1e
foreground=dcd7ba

# Normal colors (Gruvbox Dark Hard)
regular0=1d2021   # bg0_hard
regular1=cc241d   # red
regular2=98971a   # green
regular3=d79921   # yellow
regular4=458588   # blue
regular5=b16286   # purple
regular6=689d6a   # aqua
regular7=a89984   # fg4

# Bright colors
bright0=928374    # gray
bright1=fb4934    # bright red
bright2=b8bb26    # bright green
bright3=fabd2f    # bright yellow
bright4=83a598    # bright blue
bright5=d3869b    # bright purple
bright6=8ec07c    # bright aqua
bright7=ebdbb2    # fg1
